// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package tasks_module.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the Tasks_Module module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder login_microflowBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Tasks_Module.Login_microflow");
		return builder;
	}

	public static tasks_module.proxies.Login login_microflow(IContext context)
	{
		Object result = login_microflowBuilder().execute(context);
		return result == null ? null : tasks_module.proxies.Login.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder newAttachmentBuilder(
		myfirstmodule.proxies.Assets _assets
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Tasks_Module.NewAttachment");
		builder = builder.withParam("Assets", _assets);
		return builder;
	}

	public static void newAttachment(
		IContext context,
		myfirstmodule.proxies.Assets _assets
	)
	{
		newAttachmentBuilder(
				_assets
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder selectLowpriorityBuilder(
		myfirstmodule.proxies.Tasks_of_User _tasks_of_User
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Tasks_Module.SelectLowpriority");
		builder = builder.withParam("Tasks_of_User", _tasks_of_User);
		return builder;
	}

	public static void selectLowpriority(
		IContext context,
		myfirstmodule.proxies.Tasks_of_User _tasks_of_User
	)
	{
		selectLowpriorityBuilder(
				_tasks_of_User
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder selectTodoStatusBuilder(
		myfirstmodule.proxies.Tasks_of_User _tasks_of_User
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Tasks_Module.SelectTodoStatus");
		builder = builder.withParam("Tasks_of_User", _tasks_of_User);
		return builder;
	}

	public static void selectTodoStatus(
		IContext context,
		myfirstmodule.proxies.Tasks_of_User _tasks_of_User
	)
	{
		selectTodoStatusBuilder(
				_tasks_of_User
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder submitBuilder(
		myfirstmodule.proxies.SubAsset _subAsset
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Tasks_Module.Submit");
		builder = builder.withParam("SubAsset", _subAsset);
		return builder;
	}

	public static void submit(
		IContext context,
		myfirstmodule.proxies.SubAsset _subAsset
	)
	{
		submitBuilder(
				_subAsset
			)
			.execute(context);
	}
}
