// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package barcode.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the Barcode module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_TestBuilder(
		barcode.proxies.BarcodeTest _barcodeTest
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Barcode.ACT_Test");
		builder = builder.withParam("BarcodeTest", _barcodeTest);
		return builder;
	}

	public static void aCT_Test(
		IContext context,
		barcode.proxies.BarcodeTest _barcodeTest
	)
	{
		aCT_TestBuilder(
				_barcodeTest
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_GetBarcodeTestBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Barcode.DS_GetBarcodeTest");
		return builder;
	}

	public static barcode.proxies.BarcodeTest dS_GetBarcodeTest(IContext context)
	{
		Object result = dS_GetBarcodeTestBuilder().execute(context);
		return result == null ? null : barcode.proxies.BarcodeTest.initialize(context, (IMendixObject) result);
	}
}
