// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the MyFirstModule module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder asset_dashboard_microflowBuilder(
		myfirstmodule.proxies.Assets _sheet1
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.Asset_dashboard_microflow");
		builder = builder.withParam("Sheet1", _sheet1);
		return builder;
	}

	public static myfirstmodule.proxies.Assets asset_dashboard_microflow(
		IContext context,
		myfirstmodule.proxies.Assets _sheet1
	)
	{
		Object result = asset_dashboard_microflowBuilder(
				_sheet1
			)
			.execute(context);
		return result == null ? null : myfirstmodule.proxies.Assets.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder myFirstLogicBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.MyFirstLogic");
		return builder;
	}

	public static void myFirstLogic(IContext context)
	{
		myFirstLogicBuilder().execute(context);
	}
}
