// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public enum AssetTask
{
	To_do(new java.lang.String[][] { new java.lang.String[] { "en_US", "To do" } }),
	Running(new java.lang.String[][] { new java.lang.String[] { "en_US", "Running" } }),
	Completed(new java.lang.String[][] { new java.lang.String[] { "en_US", "Completed" } }),
	In_progress(new java.lang.String[][] { new java.lang.String[] { "en_US", "In progress" } }),
	Review(new java.lang.String[][] { new java.lang.String[] { "en_US", "Review" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private AssetTask(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
