// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Assets extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Assets";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		AssetName("AssetName"),
		Asset_ID("Asset_ID"),
		Uploaded_date("Uploaded_date"),
		Vender("Vender"),
		User("User"),
		Location("Location"),
		Department("Department"),
		AssetType("AssetType"),
		image("image"),
		barcode("barcode"),
		DateOfReciept("DateOfReciept"),
		PublicThumbnailPath("PublicThumbnailPath"),
		EnableCaching("EnableCaching"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		SubAsset_Assets("MyFirstModule.SubAsset_Assets");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Assets(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Assets(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject assetsMendixObject)
	{
		super(context, assetsMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, assetsMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Assets initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Assets(context, mendixObject);
	}

	public static myfirstmodule.proxies.Assets load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Assets.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Assets> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.Assets.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of AssetName
	 */
	public final java.lang.String getAssetName()
	{
		return getAssetName(getContext());
	}

	/**
	 * @param context
	 * @return value of AssetName
	 */
	public final java.lang.String getAssetName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AssetName.toString());
	}

	/**
	 * Set value of AssetName
	 * @param assetname
	 */
	public final void setAssetName(java.lang.String assetname)
	{
		setAssetName(getContext(), assetname);
	}

	/**
	 * Set value of AssetName
	 * @param context
	 * @param assetname
	 */
	public final void setAssetName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String assetname)
	{
		getMendixObject().setValue(context, MemberNames.AssetName.toString(), assetname);
	}

	/**
	 * @return value of Asset_ID
	 */
	public final java.lang.Integer getAsset_ID()
	{
		return getAsset_ID(getContext());
	}

	/**
	 * @param context
	 * @return value of Asset_ID
	 */
	public final java.lang.Integer getAsset_ID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Asset_ID.toString());
	}

	/**
	 * Set value of Asset_ID
	 * @param asset_id
	 */
	public final void setAsset_ID(java.lang.Integer asset_id)
	{
		setAsset_ID(getContext(), asset_id);
	}

	/**
	 * Set value of Asset_ID
	 * @param context
	 * @param asset_id
	 */
	public final void setAsset_ID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer asset_id)
	{
		getMendixObject().setValue(context, MemberNames.Asset_ID.toString(), asset_id);
	}

	/**
	 * @return value of Uploaded_date
	 */
	public final java.lang.String getUploaded_date()
	{
		return getUploaded_date(getContext());
	}

	/**
	 * @param context
	 * @return value of Uploaded_date
	 */
	public final java.lang.String getUploaded_date(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Uploaded_date.toString());
	}

	/**
	 * Set value of Uploaded_date
	 * @param uploaded_date
	 */
	public final void setUploaded_date(java.lang.String uploaded_date)
	{
		setUploaded_date(getContext(), uploaded_date);
	}

	/**
	 * Set value of Uploaded_date
	 * @param context
	 * @param uploaded_date
	 */
	public final void setUploaded_date(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String uploaded_date)
	{
		getMendixObject().setValue(context, MemberNames.Uploaded_date.toString(), uploaded_date);
	}

	/**
	 * @return value of Vender
	 */
	public final java.lang.String getVender()
	{
		return getVender(getContext());
	}

	/**
	 * @param context
	 * @return value of Vender
	 */
	public final java.lang.String getVender(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Vender.toString());
	}

	/**
	 * Set value of Vender
	 * @param vender
	 */
	public final void setVender(java.lang.String vender)
	{
		setVender(getContext(), vender);
	}

	/**
	 * Set value of Vender
	 * @param context
	 * @param vender
	 */
	public final void setVender(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String vender)
	{
		getMendixObject().setValue(context, MemberNames.Vender.toString(), vender);
	}

	/**
	 * @return value of User
	 */
	public final java.lang.String getUser()
	{
		return getUser(getContext());
	}

	/**
	 * @param context
	 * @return value of User
	 */
	public final java.lang.String getUser(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.User.toString());
	}

	/**
	 * Set value of User
	 * @param user
	 */
	public final void setUser(java.lang.String user)
	{
		setUser(getContext(), user);
	}

	/**
	 * Set value of User
	 * @param context
	 * @param user
	 */
	public final void setUser(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String user)
	{
		getMendixObject().setValue(context, MemberNames.User.toString(), user);
	}

	/**
	 * @return value of Location
	 */
	public final java.lang.String getLocation()
	{
		return getLocation(getContext());
	}

	/**
	 * @param context
	 * @return value of Location
	 */
	public final java.lang.String getLocation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Location.toString());
	}

	/**
	 * Set value of Location
	 * @param location
	 */
	public final void setLocation(java.lang.String location)
	{
		setLocation(getContext(), location);
	}

	/**
	 * Set value of Location
	 * @param context
	 * @param location
	 */
	public final void setLocation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String location)
	{
		getMendixObject().setValue(context, MemberNames.Location.toString(), location);
	}

	/**
	 * Get value of Department
	 * @param department
	 */
	public final myfirstmodule.proxies.Department getDepartment()
	{
		return getDepartment(getContext());
	}

	/**
	 * @param context
	 * @return value of Department
	 */
	public final myfirstmodule.proxies.Department getDepartment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Department.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.Department.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Department
	 * @param department
	 */
	public final void setDepartment(myfirstmodule.proxies.Department department)
	{
		setDepartment(getContext(), department);
	}

	/**
	 * Set value of Department
	 * @param context
	 * @param department
	 */
	public final void setDepartment(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Department department)
	{
		if (department != null) {
			getMendixObject().setValue(context, MemberNames.Department.toString(), department.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Department.toString(), null);
		}
	}

	/**
	 * Get value of AssetType
	 * @param assettype
	 */
	public final myfirstmodule.proxies.AssetType getAssetType()
	{
		return getAssetType(getContext());
	}

	/**
	 * @param context
	 * @return value of AssetType
	 */
	public final myfirstmodule.proxies.AssetType getAssetType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.AssetType.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.AssetType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of AssetType
	 * @param assettype
	 */
	public final void setAssetType(myfirstmodule.proxies.AssetType assettype)
	{
		setAssetType(getContext(), assettype);
	}

	/**
	 * Set value of AssetType
	 * @param context
	 * @param assettype
	 */
	public final void setAssetType(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.AssetType assettype)
	{
		if (assettype != null) {
			getMendixObject().setValue(context, MemberNames.AssetType.toString(), assettype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.AssetType.toString(), null);
		}
	}

	/**
	 * @return value of image
	 */
	public final java.lang.String getimage()
	{
		return getimage(getContext());
	}

	/**
	 * @param context
	 * @return value of image
	 */
	public final java.lang.String getimage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.image.toString());
	}

	/**
	 * Set value of image
	 * @param image
	 */
	public final void setimage(java.lang.String image)
	{
		setimage(getContext(), image);
	}

	/**
	 * Set value of image
	 * @param context
	 * @param image
	 */
	public final void setimage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String image)
	{
		getMendixObject().setValue(context, MemberNames.image.toString(), image);
	}

	/**
	 * @return value of barcode
	 */
	public final java.lang.String getbarcode()
	{
		return getbarcode(getContext());
	}

	/**
	 * @param context
	 * @return value of barcode
	 */
	public final java.lang.String getbarcode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.barcode.toString());
	}

	/**
	 * Set value of barcode
	 * @param barcode
	 */
	public final void setbarcode(java.lang.String barcode)
	{
		setbarcode(getContext(), barcode);
	}

	/**
	 * Set value of barcode
	 * @param context
	 * @param barcode
	 */
	public final void setbarcode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String barcode)
	{
		getMendixObject().setValue(context, MemberNames.barcode.toString(), barcode);
	}

	/**
	 * @return value of DateOfReciept
	 */
	public final java.util.Date getDateOfReciept()
	{
		return getDateOfReciept(getContext());
	}

	/**
	 * @param context
	 * @return value of DateOfReciept
	 */
	public final java.util.Date getDateOfReciept(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DateOfReciept.toString());
	}

	/**
	 * Set value of DateOfReciept
	 * @param dateofreciept
	 */
	public final void setDateOfReciept(java.util.Date dateofreciept)
	{
		setDateOfReciept(getContext(), dateofreciept);
	}

	/**
	 * Set value of DateOfReciept
	 * @param context
	 * @param dateofreciept
	 */
	public final void setDateOfReciept(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date dateofreciept)
	{
		getMendixObject().setValue(context, MemberNames.DateOfReciept.toString(), dateofreciept);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of SubAsset_Assets
	 */
	public final java.util.List<myfirstmodule.proxies.SubAsset> getSubAsset_Assets() throws com.mendix.core.CoreException
	{
		return getSubAsset_Assets(getContext());
	}

	/**
	 * @param context
	 * @return value of SubAsset_Assets
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<myfirstmodule.proxies.SubAsset> getSubAsset_Assets(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.SubAsset> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.SubAsset_Assets.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(myfirstmodule.proxies.SubAsset.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of SubAsset_Assets
	 * @param subasset_assets
	 */
	public final void setSubAsset_Assets(java.util.List<myfirstmodule.proxies.SubAsset> subasset_assets)
	{
		setSubAsset_Assets(getContext(), subasset_assets);
	}

	/**
	 * Set value of SubAsset_Assets
	 * @param context
	 * @param subasset_assets
	 */
	public final void setSubAsset_Assets(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<myfirstmodule.proxies.SubAsset> subasset_assets)
	{
		var identifiers = subasset_assets
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.SubAsset_Assets.toString(), identifiers);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Assets that = (myfirstmodule.proxies.Assets) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
