// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public enum Department
{
	IT(new java.lang.String[][] { new java.lang.String[] { "en_US", "IT" } }),
	Finance(new java.lang.String[][] { new java.lang.String[] { "en_US", "Finance" } }),
	Sales(new java.lang.String[][] { new java.lang.String[] { "en_US", "Sales" } }),
	Design(new java.lang.String[][] { new java.lang.String[] { "en_US", "Design" } }),
	Admin(new java.lang.String[][] { new java.lang.String[] { "en_US", "Admin" } }),
	Accounting(new java.lang.String[][] { new java.lang.String[] { "en_US", "Accounting" } }),
	Marketing(new java.lang.String[][] { new java.lang.String[] { "en_US", "Marketing" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private Department(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
