// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class User implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject userMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.User";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		ContactNo("ContactNo"),
		EmailAddress("EmailAddress"),
		Location("Location"),
		Department("Department"),
		AssignedAsset("AssignedAsset"),
		Photo_User("MyFirstModule.Photo_User");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public User(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected User(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject userMendixObject)
	{
		if (userMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, userMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.userMendixObject = userMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.User initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.User(context, mendixObject);
	}

	public static myfirstmodule.proxies.User load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.User.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.User> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.User.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of ContactNo
	 */
	public final java.lang.String getContactNo()
	{
		return getContactNo(getContext());
	}

	/**
	 * @param context
	 * @return value of ContactNo
	 */
	public final java.lang.String getContactNo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ContactNo.toString());
	}

	/**
	 * Set value of ContactNo
	 * @param contactno
	 */
	public final void setContactNo(java.lang.String contactno)
	{
		setContactNo(getContext(), contactno);
	}

	/**
	 * Set value of ContactNo
	 * @param context
	 * @param contactno
	 */
	public final void setContactNo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String contactno)
	{
		getMendixObject().setValue(context, MemberNames.ContactNo.toString(), contactno);
	}

	/**
	 * @return value of EmailAddress
	 */
	public final java.lang.String getEmailAddress()
	{
		return getEmailAddress(getContext());
	}

	/**
	 * @param context
	 * @return value of EmailAddress
	 */
	public final java.lang.String getEmailAddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EmailAddress.toString());
	}

	/**
	 * Set value of EmailAddress
	 * @param emailaddress
	 */
	public final void setEmailAddress(java.lang.String emailaddress)
	{
		setEmailAddress(getContext(), emailaddress);
	}

	/**
	 * Set value of EmailAddress
	 * @param context
	 * @param emailaddress
	 */
	public final void setEmailAddress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String emailaddress)
	{
		getMendixObject().setValue(context, MemberNames.EmailAddress.toString(), emailaddress);
	}

	/**
	 * @return value of Location
	 */
	public final java.lang.String getLocation()
	{
		return getLocation(getContext());
	}

	/**
	 * @param context
	 * @return value of Location
	 */
	public final java.lang.String getLocation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Location.toString());
	}

	/**
	 * Set value of Location
	 * @param location
	 */
	public final void setLocation(java.lang.String location)
	{
		setLocation(getContext(), location);
	}

	/**
	 * Set value of Location
	 * @param context
	 * @param location
	 */
	public final void setLocation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String location)
	{
		getMendixObject().setValue(context, MemberNames.Location.toString(), location);
	}

	/**
	 * Get value of Department
	 * @param department
	 */
	public final myfirstmodule.proxies.Department getDepartment()
	{
		return getDepartment(getContext());
	}

	/**
	 * @param context
	 * @return value of Department
	 */
	public final myfirstmodule.proxies.Department getDepartment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Department.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.Department.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Department
	 * @param department
	 */
	public final void setDepartment(myfirstmodule.proxies.Department department)
	{
		setDepartment(getContext(), department);
	}

	/**
	 * Set value of Department
	 * @param context
	 * @param department
	 */
	public final void setDepartment(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Department department)
	{
		if (department != null) {
			getMendixObject().setValue(context, MemberNames.Department.toString(), department.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Department.toString(), null);
		}
	}

	/**
	 * @return value of AssignedAsset
	 */
	public final java.lang.String getAssignedAsset()
	{
		return getAssignedAsset(getContext());
	}

	/**
	 * @param context
	 * @return value of AssignedAsset
	 */
	public final java.lang.String getAssignedAsset(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AssignedAsset.toString());
	}

	/**
	 * Set value of AssignedAsset
	 * @param assignedasset
	 */
	public final void setAssignedAsset(java.lang.String assignedasset)
	{
		setAssignedAsset(getContext(), assignedasset);
	}

	/**
	 * Set value of AssignedAsset
	 * @param context
	 * @param assignedasset
	 */
	public final void setAssignedAsset(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String assignedasset)
	{
		getMendixObject().setValue(context, MemberNames.AssignedAsset.toString(), assignedasset);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Photo_User
	 */
	public final myfirstmodule.proxies.Photo getPhoto_User() throws com.mendix.core.CoreException
	{
		return getPhoto_User(getContext());
	}

	/**
	 * @param context
	 * @return value of Photo_User
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Photo getPhoto_User(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Photo result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Photo_User.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Photo.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Photo_User
	 * @param photo_user
	 */
	public final void setPhoto_User(myfirstmodule.proxies.Photo photo_user)
	{
		setPhoto_User(getContext(), photo_user);
	}

	/**
	 * Set value of Photo_User
	 * @param context
	 * @param photo_user
	 */
	public final void setPhoto_User(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Photo photo_user)
	{
		if (photo_user == null) {
			getMendixObject().setValue(context, MemberNames.Photo_User.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Photo_User.toString(), photo_user.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return userMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.User that = (myfirstmodule.proxies.User) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
